----------------------------TAREA------------------------------------------------
-- QUISIERA SABER COD_TRABAJADOR, APELLIDO DE TRABAJADOR, NOMBRE DEL DEPARTAMENTO ASOCIADO,
-- Y EN CASO DE NO ESTAR ASOCIADO A UN DEPARTAMENTO, EL TRABAJADOR DEBE MOSTRARSE IGUAL.


-- QUISIERA SABER DEL TRABAJADOR: NOMBRE CONCATENADO CON EL APELLIDO, SU CÓDIGO, 
-- EL NOMBRE DE SU DEPARTAMENTO ASOCIADO Y EL NOMBRE DEL JEFE ASOCIADO A DICHO
-- DEPARTAMENTO ADEMÁS DE LA CIUDAD EN LA QUE SE ENCUENTRA Y ADEMÁS DEL NOMBRE 
-- DE SU CARGO.


SELECT E.EMPLOYEE_ID, E.LAST_NAME, D.DEPARTMENT_NAME, E.DEPARTMENT_ID
FROM OEHR_EMPLOYEES E LEFT JOIN OEHR_DEPARTMENTS D ON(E.DEPARTMENT_ID = D.DEPARTMENT_ID)

SELECT CONCAT(E.FIRST_NAME,CONCAT(' ',E.LAST_NAME)) AS "NOMBRE", E.EMPLOYEE_ID AS "CODIGO EMPLEADO", 
D.DEPARTMENT_NAME AS "NOMBRE DEPARTAMENTO", E.MANAGER_ID AS "JEFE", L.CITY AS "CIUDAD", J.JOB_TITLE AS "CARGO"
FROM OEHR_EMPLOYEES E LEFT JOIN OEHR_DEPARTMENTS D ON(D.MANAGER_ID = E.MANAGER_ID) 
LEFT JOIN OEHR_LOCATIONS L ON(L.LOCATION_ID = D.LOCATION_ID) JOIN OEHR_JOBS J ON(E.JOB_ID = J.JOB_ID)