--Tarea 1
--QUISIERA VER LOS DATOS DE TODOS AQUELLOS DEPARTAMENTOS EN LOS QUE SU 
--NOMBRE TENGA COMO SEGUNDA LETRA LA A Y TERMINE CON LA LETRA S

SELECT *
FROM OEHR_DEPARTMENTS
WHERE DEPARTMENT_NAME LIKE '_a%s';

-- TAREA 2
--QUISIERA VER COD, NOMGBRE Y APELLIDO CONCATENADOS, DE TODOS AQUELLOS
--TRABAJADORES, DONDE SU CARGO TTENGA COMO PENÚLTIMA LETRA LA A

SELECT EMPLOYEE_ID, FIRST_NAME||' '||LAST_NAME
FROM OEHR_EMPLOYEES
WHERE DEPARTMENT_NAME IN (SELECT DEPARTMENT_NAME FROM OEHR_DEPARTMENTS WHERE DEPARTMENT_NAME LIKE %A_);

--TAREA 3
--QUISIERA VER COD, NOMBRE Y APELLIDOS CONCATENADOS, DE TODOS AQUELLOS
--TRABAJADORES, DONDE SU APELLIDO NO TENGA CONTENIDA LA LETRA A

SELECT EMPLOYEE_ID, FIRST_NAME||' '||LAST_NAME
FROM OEHR_EMPLOYEES
WHERE LAST_NAME NOT LIKE '%a%' AND LAST_NAME NOT LIKE '%A%';
